name: Publicar en NPM automáticamente

on:
    release:
        types: [published]

jobs:
    build-and-publish:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            id-token: write

        steps:
            - name: Clonar el repositorio
              uses: actions/checkout@v4

            - name: Configurar Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "24.x"

            - name: Instalar dependencias
              run: npm install --legacy-peer-deps

            - name: Publicar la nueva versión en NPM
              run: npm publish --provenance --tag latest
